# This is a basic workflow to help you get started with Actions

name: My-GitHubActions-Basics

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
      - development

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my_testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Print Hello message in Testing
        run: echo "Hello world form Testing job"
  my_deploy:
    runs-on: ubuntu-latest
    needs:
      - my_testing
    steps:
      - name: Print Hello message in Deploy
        run: echo "Hello world from Deploy job"
      
